# Generated by Django 4.2.1 on 2024-05-11 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Favourite_movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='image',
            field=models.ImageField(null=True, upload_to='images/directors/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(null=True, upload_to='images/movies/'),
        ),
    ]
