# Generated by Django 4.2.1 on 2024-05-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Favourite_movies', '0002_director_image_movie_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='story',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
